apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/sandboxdv/catalog-service/k8s?ref=main

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/sandboxdv/catalog-service
  newTag: 8a9cce0540af74e0bd12de93e2a07861093acac9

replicas:
- count: 2
  name: catalog-service
